### ISSUE TITLE
Add font support

### ISSUE THREAD

**Issue by crashmax-dev** [Pisyukaev/twitch-sub-goal#20]
I suggested using [fontsource](https://fontsource.org/docs/api/introduction):
https://codesandbox.io/s/fontsource-api-n0lv3s?file=/src/App.tsx or https://github.com/crashmax-dev/fontsource-api

<details><summary>I also created this issue to discuss how to properly implement this.</summary>
<p>
Если не против, можно было бы на русском вести обсуждение.
</p>
</details>

**Comment by Pisyukaev** [comment]
Думаю, можно вести обсуждение и на русском

Спасибо за пример! Я уже сейчас работаю над тем, чтобы внедрить это в расширение

**Comment by crashmax-dev** [comment]
Если уже есть наработки, то предлагаю создать PR

**Comment by Pisyukaev** [comment]
Есть, но еще не готово, для оформления PR
