### ISSUE TITLE
Function to generate css styles

### ISSUE THREAD

**Issue by Pisyukaev** [Pisyukaev/twitch-sub-goal#23]
Я использую вот такую функцию для генерации стилей

```ts
export const selectors: Record<string, string> = {
  widget: '.goal_widget',
  progressBar: '.goal_widget__progress_bar',
  image: '.goal_widget__image.tw-image',
  leftText: '.goal_widget__metadata > div:first-child',
  rightText: '.goal_widget__contributions',
  counterText: '.goal_widget__contributions > span'
}

export type WidgetOptions = {
  widget: {
    backgroundColor: string
    borderRadius: string
    borderWidth: string
    borderStyle: string
    borderColor: string
  }
  ...
}

export function transformOptionsToStyles(styles: WidgetOptions) {
  return Object.entries(styles)
    .reduce<string[]>((classes, [selector, styles]) => {
      const classStyles = Object.entries(styles).reduce<string[]>(
        (styles, [property, value]) => {
          styles.push(
            `\n${decamelize(property, {
              separator: '-'
            })}: ${value} !important;`
          )
          return styles
        },
        []
      )
      classes.push(`${selectors[selector]} {${classStyles.join('')}}`)
      return classes
    }, [])
    .join('\n ')
}
```

и чтобы не плодить лишние поля в настройках (property), пришлось поставить библиотеку https://github.com/sindresorhus/decamelize для трансформации camelCase: `backgroundColor` -> `background-color`

_Originally posted by @crashmax-dev in https://github.com/Pisyukaev/twitch-sub-goal/issues/21#issuecomment-1520583295_

**Comment by crashmax-dev** [comment]
@Pisyukaev 👀

**Comment by Pisyukaev** [comment]
@crashmax-dev , Я тут попробовал перейти на ```camelCase```, чтобы сделать, как ты предлагаешь, но с этим много возни. Так как у меня дефолтные стили и измененные стили сейчас хранятся все в ```kebab-case```. И чтобы ничего не отломать, мне придется добавлять костыль на обратную совместимость. 
И получится, что мне сначала надо будет из ```kebab-case``` переделать все имеющиеся(сохраненные) стили в ```camelCase```, а потом при импорте делать обратную трансформацию. Как-то слишком геморно
