### ISSUE TITLE
Publishing extension in Firefox Addons

### ISSUE THREAD

**Issue by crashmax-dev** [Pisyukaev/twitch-sub-goal#7]
Supported Plasmo Framework targets: https://docs.plasmo.com/framework/workflows/faq#what-are-the-officially-supported-browser-targets

https://docs.plasmo.com/framework/workflows/build#with-a-specific-target

**Comment by Pisyukaev** [comment]
Extension was publish in Firefox Addons
https://addons.mozilla.org/ru/firefox/addon/twitch-sub-goal/
